/**
 * Editor.jsx — Reusable Editor.js wrapper component
 *
 * LEARNING NOTES:
 * ───────────────
 * Editor.js is a "block-style" editor. Instead of outputting a blob of HTML,
 * it stores your content as structured JSON like this:
 *
 *   {
 *     "time": 1719999999999,      ← Unix timestamp (ms) of last edit
 *     "version": "2.30.0",        ← Editor.js version that wrote this data
 *     "blocks": [                 ← Array of content blocks (the real content)
 *       {
 *         "id": "abc123",         ← Unique block ID (generated by Editor.js)
 *         "type": "header",       ← Which tool produced this block
 *         "data": {               ← Tool-specific payload
 *           "text": "Hello",
 *           "level": 2
 *         }
 *       },
 *       ...
 *     ]
 *   }
 *
 * This JSON is what we store in the DB and render back in NoteView.jsx.
 */

import { useEffect, useRef } from 'react';
import EditorJS from '@editorjs/editorjs';
import Header from '@editorjs/header';
import List from '@editorjs/list';
import Checklist from '@editorjs/checklist';
import Quote from '@editorjs/quote';
import ImageTool from '@editorjs/image';

/**
 * Props:
 *   editorRef  — a ref the parent holds; we attach { save() } to it so the
 *                parent can call editorRef.current.save() to get the JSON.
 *   initialData — the Editor.js JSON to pre-populate (for edit mode).
 *                 Leave undefined for a blank editor (create mode).
 */
export default function Editor({ editorRef, initialData }) {
  // holderRef points to the <div> that Editor.js mounts itself into.
  // Editor.js is NOT a React component — it needs a real DOM node.
  const holderRef = useRef(null);

  // instanceRef holds the Editor.js instance so we can call .destroy() later.
  const instanceRef = useRef(null);

  useEffect(() => {
    // Guard: don't initialise twice (React StrictMode calls useEffect twice in dev)
    if (instanceRef.current) return;

    // ── CREATE THE EDITOR INSTANCE ─────────────────────────────────────────
    const editor = new EditorJS({
      /**
       * holder — the DOM element ID (or the element itself) where Editor.js
       * renders its toolbar and content blocks.
       */
      holder: holderRef.current,

      /**
       * data — pre-existing Editor.js JSON to load on mount.
       * Pass undefined (or omit) to start with an empty editor.
       */
      data: initialData || undefined,

      /**
       * placeholder — shown when the editor is empty.
       */
      placeholder: 'Start writing your note…',

      /**
       * autofocus — move the cursor into the editor automatically on mount.
       */
      autofocus: true,

      /**
       * tools — registers the block tools available in the editor toolbar.
       *
       * Each key becomes the block "type" in the saved JSON.
       * Each value is either:
       *   • the Tool class directly (uses all defaults), or
       *   • an object with { class, config } for custom settings.
       */
      tools: {
        /**
         * HEADER TOOL
         * Adds H1–H6 heading blocks.
         * Saved JSON shape:  { type: "header", data: { text: "...", level: 2 } }
         *
         * config.levels  — which heading levels to show in the popup (1–6).
         * config.defaultLevel — which level is pre-selected when you click the tool.
         */
        header: {
          class: Header,
          config: {
            levels: [1, 2, 3, 4],
            defaultLevel: 2,
          },
        },

        /**
         * LIST TOOL
         * Ordered and unordered lists.
         * Saved JSON shape:
         *   { type: "list", data: { style: "ordered"|"unordered", items: [...] } }
         *
         * config.defaultStyle — which list style is used when you click the tool.
         */
        list: {
          class: List,
          inlineToolbar: true,  // Allow bold/italic inside list items
          config: {
            defaultStyle: 'unordered',
          },
        },

        /**
         * CHECKLIST TOOL
         * A to-do list where each item has a checked/unchecked state.
         * Saved JSON shape:
         *   { type: "checklist", data: { items: [{ text: "...", checked: false }] } }
         */
        checklist: {
          class: Checklist,
          inlineToolbar: true,
        },

        /**
         * QUOTE TOOL
         * A styled blockquote with an optional caption.
         * Saved JSON shape:
         *   { type: "quote", data: { text: "...", caption: "...", alignment: "left" } }
         *
         * config.quotePlaceholder / captionPlaceholder — placeholder text.
         */
        quote: {
          class: Quote,
          inlineToolbar: true,
          config: {
            quotePlaceholder: 'Enter a quote…',
            captionPlaceholder: 'Quote author',
          },
        },

        /**
         * IMAGE TOOL
         * Handles image uploads. Clicking the tool opens a file picker.
         * After the user picks a file, the tool POSTs it to our backend and
         * receives { success: 1, file: { url } } back.
         *
         * Saved JSON shape:
         *   {
         *     type: "image",
         *     data: {
         *       file: { url: "http://..." },
         *       caption: "...",
         *       withBorder: false,
         *       stretched: false,
         *       withBackground: false
         *     }
         *   }
         *
         * config.endpoints.byFile — URL the tool POSTs the file to.
         *   The backend MUST return { success: 1, file: { url } }.
         *
         * config.additionalRequestHeaders — extra headers sent with the upload
         *   (add Authorization: Bearer ... here if you add auth later).
         */
        image: {
          class: ImageTool,
          config: {
            endpoints: {
              byFile: 'http://localhost:3001/upload-image',
            },
          },
        },
      }, // end tools

      /**
       * onReady — called once when the editor has fully initialised.
       * Useful for logging or UI setup after the editor is ready.
       */
      onReady: () => {
        console.log('[Editor.js] Ready ✓');
      },

      /**
       * onChange — called after every block change (typing, adding, deleting).
       * We don't auto-save here — the parent calls editorRef.current.save()
       * on button click instead, which is simpler for a learning project.
       */
      onChange: () => {
        // console.log('[Editor.js] Content changed');
      },
    }); // end new EditorJS(...)

    instanceRef.current = editor;

    // Expose a save() method to the parent via the passed-in ref.
    // The parent calls: const data = await editorRef.current.save()
    // editor.save() returns a Promise<OutputData> (the JSON object).
    if (editorRef) {
      editorRef.current = {
        save: () => editor.save(),
      };
    }

    // ── CLEANUP ───────────────────────────────────────────────────────────
    // When the component unmounts (or React re-runs the effect in StrictMode),
    // destroy the editor to release DOM listeners and prevent memory leaks.
    return () => {
      if (instanceRef.current && instanceRef.current.destroy) {
        instanceRef.current.destroy();
        instanceRef.current = null;
      }
    };
  }, []); // Empty deps — run once on mount only

  return (
    <div
      ref={holderRef}
      id="editorjs-holder"
      style={{
        border: '1px solid #e0e0e0',
        borderRadius: '8px',
        minHeight: '300px',
        padding: '16px',
        backgroundColor: '#fff',
      }}
    />
  );
}
